### PR TITLE
Removing duplicate LibraryApplication class, setting mainClass and bean-definition-overriding

### PR DESCRIPTION
**Pull request by katHermanova**

### CODE REVIEW

**Comment by xpalenik** [comment]
Ahoj, 
rozmýšľal som nad tým _spring.main.allow-bean-definition-overriding_ a v [tomto článku](https://brudenko.com/spring-bean-override) som našiel nasledovné doporučenia.

1. First of all I strongly suggest you to **enable** this configuration: **spring.main.allow-bean-definition-overriding=false** It will immediately give you an information that you have beans with same names and conflicts between them.
2. If this code is yours and in any way it’s possible to change names of beans - just do it and Inject that one which you need. And you will never face with this issue.
3. If for some reasons point 2 is not a case for you - I suggest to try to exclude wrong bean. As you can see it’s very difficult to predict which bean will be overridden, so would be much better just to remove it from context.

Ak by to bolo možné, rád by som sa teda vyhol tomu _spring.main.allow-bean-definition-overriding: true_ a riešil to nejak inak - najskôr podľa bodu 2 hore, podľa školského projektu, alebo tutoriálu.

Môžeš mi prosím bližšie popísať kde k tomu problému dochádza a prečo bolo nutné to zmeniť?

**Comment by xpalenik** [comment]
Ja momentálne v `master` vidím len tento problém keď sa pokúsim spustiť `LibraryApplication.java` v balíku library-rest.

> Description:
> 
> Parameter 0 of constructor in cz.muni.fi.pa165.library.services.MappingService required a bean of type 'com.github.dozermapper.core.Mapper' that could not be found.
> 
> 
> Action:
> 
> Consider defining a bean of type 'com.github.dozermapper.core.Mapper' in your configuration.

Na problém s bean definition overriding som zatiaľ nenarazil.

**Comment by katHermanova** [comment]
myslim, ze spustas triedu LibraryApplication, ktora tam uz bola a neodstranili sme ju a nie tu, ktoru nie tu ktoru si vytvoril v library-service

**Comment by xpalenik** [comment]
Tak som to práve opravil a už mi beží Tomcat na library-rest.

**Pull request closed without merging**
